name: Deploy on server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << EOF
            cd apps
            cd nextjs-folder-structure-example
            git pull
            npm ci
            npm run build
            pm2 restart nextjs-example
          EOF
